// Code generated by protoc-gen-go. DO NOT EDIT.
// source: docs/proto/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{0}
}

func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type AuthRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{1}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AuthResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{2}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ResetRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetRequest) Reset()         { *m = ResetRequest{} }
func (m *ResetRequest) String() string { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()    {}
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{3}
}

func (m *ResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetRequest.Unmarshal(m, b)
}
func (m *ResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetRequest.Marshal(b, m, deterministic)
}
func (m *ResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetRequest.Merge(m, src)
}
func (m *ResetRequest) XXX_Size() int {
	return xxx_messageInfo_ResetRequest.Size(m)
}
func (m *ResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetRequest proto.InternalMessageInfo

func (m *ResetRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ResetRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ResetResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetResponse) Reset()         { *m = ResetResponse{} }
func (m *ResetResponse) String() string { return proto.CompactTextString(m) }
func (*ResetResponse) ProtoMessage()    {}
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{4}
}

func (m *ResetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetResponse.Unmarshal(m, b)
}
func (m *ResetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetResponse.Marshal(b, m, deterministic)
}
func (m *ResetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetResponse.Merge(m, src)
}
func (m *ResetResponse) XXX_Size() int {
	return xxx_messageInfo_ResetResponse.Size(m)
}
func (m *ResetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetResponse proto.InternalMessageInfo

func (m *ResetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SubNet struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask                 string   `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubNet) Reset()         { *m = SubNet{} }
func (m *SubNet) String() string { return proto.CompactTextString(m) }
func (*SubNet) ProtoMessage()    {}
func (*SubNet) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{5}
}

func (m *SubNet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubNet.Unmarshal(m, b)
}
func (m *SubNet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubNet.Marshal(b, m, deterministic)
}
func (m *SubNet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubNet.Merge(m, src)
}
func (m *SubNet) XXX_Size() int {
	return xxx_messageInfo_SubNet.Size(m)
}
func (m *SubNet) XXX_DiscardUnknown() {
	xxx_messageInfo_SubNet.DiscardUnknown(m)
}

var xxx_messageInfo_SubNet proto.InternalMessageInfo

func (m *SubNet) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *SubNet) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

type BlacklistAddRequest struct {
	SubNet               *SubNet  `protobuf:"bytes,1,opt,name=sub_net,json=subNet,proto3" json:"sub_net,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlacklistAddRequest) Reset()         { *m = BlacklistAddRequest{} }
func (m *BlacklistAddRequest) String() string { return proto.CompactTextString(m) }
func (*BlacklistAddRequest) ProtoMessage()    {}
func (*BlacklistAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{6}
}

func (m *BlacklistAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlacklistAddRequest.Unmarshal(m, b)
}
func (m *BlacklistAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlacklistAddRequest.Marshal(b, m, deterministic)
}
func (m *BlacklistAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlacklistAddRequest.Merge(m, src)
}
func (m *BlacklistAddRequest) XXX_Size() int {
	return xxx_messageInfo_BlacklistAddRequest.Size(m)
}
func (m *BlacklistAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlacklistAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlacklistAddRequest proto.InternalMessageInfo

func (m *BlacklistAddRequest) GetSubNet() *SubNet {
	if m != nil {
		return m.SubNet
	}
	return nil
}

type BlacklistAddResponse struct {
	Data                 *BaseResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BlacklistAddResponse) Reset()         { *m = BlacklistAddResponse{} }
func (m *BlacklistAddResponse) String() string { return proto.CompactTextString(m) }
func (*BlacklistAddResponse) ProtoMessage()    {}
func (*BlacklistAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{7}
}

func (m *BlacklistAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlacklistAddResponse.Unmarshal(m, b)
}
func (m *BlacklistAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlacklistAddResponse.Marshal(b, m, deterministic)
}
func (m *BlacklistAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlacklistAddResponse.Merge(m, src)
}
func (m *BlacklistAddResponse) XXX_Size() int {
	return xxx_messageInfo_BlacklistAddResponse.Size(m)
}
func (m *BlacklistAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlacklistAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlacklistAddResponse proto.InternalMessageInfo

func (m *BlacklistAddResponse) GetData() *BaseResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type BlacklistRemoveRequest struct {
	SubNet               *SubNet  `protobuf:"bytes,1,opt,name=sub_net,json=subNet,proto3" json:"sub_net,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlacklistRemoveRequest) Reset()         { *m = BlacklistRemoveRequest{} }
func (m *BlacklistRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*BlacklistRemoveRequest) ProtoMessage()    {}
func (*BlacklistRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{8}
}

func (m *BlacklistRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlacklistRemoveRequest.Unmarshal(m, b)
}
func (m *BlacklistRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlacklistRemoveRequest.Marshal(b, m, deterministic)
}
func (m *BlacklistRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlacklistRemoveRequest.Merge(m, src)
}
func (m *BlacklistRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_BlacklistRemoveRequest.Size(m)
}
func (m *BlacklistRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlacklistRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlacklistRemoveRequest proto.InternalMessageInfo

func (m *BlacklistRemoveRequest) GetSubNet() *SubNet {
	if m != nil {
		return m.SubNet
	}
	return nil
}

type BlacklistRemoveResponse struct {
	Data                 *BaseResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BlacklistRemoveResponse) Reset()         { *m = BlacklistRemoveResponse{} }
func (m *BlacklistRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*BlacklistRemoveResponse) ProtoMessage()    {}
func (*BlacklistRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{9}
}

func (m *BlacklistRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlacklistRemoveResponse.Unmarshal(m, b)
}
func (m *BlacklistRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlacklistRemoveResponse.Marshal(b, m, deterministic)
}
func (m *BlacklistRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlacklistRemoveResponse.Merge(m, src)
}
func (m *BlacklistRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_BlacklistRemoveResponse.Size(m)
}
func (m *BlacklistRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlacklistRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlacklistRemoveResponse proto.InternalMessageInfo

func (m *BlacklistRemoveResponse) GetData() *BaseResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type WhitelistAddRequest struct {
	SubNet               *SubNet  `protobuf:"bytes,1,opt,name=sub_net,json=subNet,proto3" json:"sub_net,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhitelistAddRequest) Reset()         { *m = WhitelistAddRequest{} }
func (m *WhitelistAddRequest) String() string { return proto.CompactTextString(m) }
func (*WhitelistAddRequest) ProtoMessage()    {}
func (*WhitelistAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{10}
}

func (m *WhitelistAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhitelistAddRequest.Unmarshal(m, b)
}
func (m *WhitelistAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhitelistAddRequest.Marshal(b, m, deterministic)
}
func (m *WhitelistAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistAddRequest.Merge(m, src)
}
func (m *WhitelistAddRequest) XXX_Size() int {
	return xxx_messageInfo_WhitelistAddRequest.Size(m)
}
func (m *WhitelistAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistAddRequest proto.InternalMessageInfo

func (m *WhitelistAddRequest) GetSubNet() *SubNet {
	if m != nil {
		return m.SubNet
	}
	return nil
}

type WhitelistAddResponse struct {
	Data                 *BaseResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WhitelistAddResponse) Reset()         { *m = WhitelistAddResponse{} }
func (m *WhitelistAddResponse) String() string { return proto.CompactTextString(m) }
func (*WhitelistAddResponse) ProtoMessage()    {}
func (*WhitelistAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{11}
}

func (m *WhitelistAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhitelistAddResponse.Unmarshal(m, b)
}
func (m *WhitelistAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhitelistAddResponse.Marshal(b, m, deterministic)
}
func (m *WhitelistAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistAddResponse.Merge(m, src)
}
func (m *WhitelistAddResponse) XXX_Size() int {
	return xxx_messageInfo_WhitelistAddResponse.Size(m)
}
func (m *WhitelistAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistAddResponse proto.InternalMessageInfo

func (m *WhitelistAddResponse) GetData() *BaseResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type WhitelistRemoveRequest struct {
	SubNet               *SubNet  `protobuf:"bytes,1,opt,name=sub_net,json=subNet,proto3" json:"sub_net,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhitelistRemoveRequest) Reset()         { *m = WhitelistRemoveRequest{} }
func (m *WhitelistRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*WhitelistRemoveRequest) ProtoMessage()    {}
func (*WhitelistRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{12}
}

func (m *WhitelistRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhitelistRemoveRequest.Unmarshal(m, b)
}
func (m *WhitelistRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhitelistRemoveRequest.Marshal(b, m, deterministic)
}
func (m *WhitelistRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistRemoveRequest.Merge(m, src)
}
func (m *WhitelistRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_WhitelistRemoveRequest.Size(m)
}
func (m *WhitelistRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistRemoveRequest proto.InternalMessageInfo

func (m *WhitelistRemoveRequest) GetSubNet() *SubNet {
	if m != nil {
		return m.SubNet
	}
	return nil
}

type WhitelistRemoveResponse struct {
	Data                 *BaseResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WhitelistRemoveResponse) Reset()         { *m = WhitelistRemoveResponse{} }
func (m *WhitelistRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*WhitelistRemoveResponse) ProtoMessage()    {}
func (*WhitelistRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad46ed9dd822c35, []int{13}
}

func (m *WhitelistRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhitelistRemoveResponse.Unmarshal(m, b)
}
func (m *WhitelistRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhitelistRemoveResponse.Marshal(b, m, deterministic)
}
func (m *WhitelistRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistRemoveResponse.Merge(m, src)
}
func (m *WhitelistRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_WhitelistRemoveResponse.Size(m)
}
func (m *WhitelistRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistRemoveResponse proto.InternalMessageInfo

func (m *WhitelistRemoveResponse) GetData() *BaseResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*BaseResponse)(nil), "api.BaseResponse")
	proto.RegisterType((*AuthRequest)(nil), "api.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "api.AuthResponse")
	proto.RegisterType((*ResetRequest)(nil), "api.ResetRequest")
	proto.RegisterType((*ResetResponse)(nil), "api.ResetResponse")
	proto.RegisterType((*SubNet)(nil), "api.SubNet")
	proto.RegisterType((*BlacklistAddRequest)(nil), "api.BlacklistAddRequest")
	proto.RegisterType((*BlacklistAddResponse)(nil), "api.BlacklistAddResponse")
	proto.RegisterType((*BlacklistRemoveRequest)(nil), "api.BlacklistRemoveRequest")
	proto.RegisterType((*BlacklistRemoveResponse)(nil), "api.BlacklistRemoveResponse")
	proto.RegisterType((*WhitelistAddRequest)(nil), "api.WhitelistAddRequest")
	proto.RegisterType((*WhitelistAddResponse)(nil), "api.WhitelistAddResponse")
	proto.RegisterType((*WhitelistRemoveRequest)(nil), "api.WhitelistRemoveRequest")
	proto.RegisterType((*WhitelistRemoveResponse)(nil), "api.WhitelistRemoveResponse")
}

func init() {
	proto.RegisterFile("docs/proto/api.proto", fileDescriptor_fad46ed9dd822c35)
}

var fileDescriptor_fad46ed9dd822c35 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x51, 0xcf, 0xd2, 0x30,
	0x14, 0xfd, 0x18, 0x1f, 0x7c, 0x78, 0x37, 0x51, 0x0a, 0xd1, 0x39, 0x8d, 0x9a, 0x46, 0x13, 0x1f,
	0x14, 0x0c, 0xfa, 0x46, 0x34, 0x42, 0xe2, 0x2b, 0x26, 0xe3, 0xc1, 0xc4, 0x17, 0x53, 0x58, 0x23,
	0xcd, 0x80, 0x56, 0xda, 0xe1, 0x8f, 0xf1, 0xcf, 0x9a, 0xb5, 0x65, 0xe9, 0x60, 0x98, 0x8c, 0xa7,
	0xb5, 0xbd, 0x3d, 0xe7, 0x9e, 0x7b, 0xef, 0x59, 0x61, 0x90, 0xf0, 0x95, 0x1c, 0x89, 0x3d, 0x57,
	0x7c, 0x44, 0x04, 0x1b, 0xea, 0x15, 0x6a, 0x12, 0xc1, 0x30, 0x86, 0x60, 0x46, 0x24, 0x8d, 0xa9,
	0x14, 0x7c, 0x27, 0x29, 0x42, 0x70, 0x9b, 0x10, 0x45, 0xc2, 0xc6, 0xcb, 0xc6, 0x9b, 0x7b, 0xb1,
	0x5e, 0xe3, 0x6f, 0xe0, 0x4f, 0x33, 0xb5, 0x8e, 0xe9, 0xef, 0x8c, 0x4a, 0x85, 0x06, 0xd0, 0xda,
	0xf0, 0x5f, 0x6c, 0x67, 0xef, 0x98, 0x0d, 0x8a, 0xa0, 0x23, 0x88, 0x94, 0x7f, 0xf8, 0x3e, 0x09,
	0x3d, 0x1d, 0x28, 0xf6, 0xa8, 0x0b, 0x1e, 0x13, 0x61, 0x53, 0x9f, 0x7a, 0x4c, 0xe0, 0xe7, 0x10,
	0x18, 0x42, 0x9b, 0xb4, 0x0b, 0x1e, 0x4f, 0x35, 0x5d, 0x27, 0xf6, 0x78, 0x8a, 0x3f, 0x42, 0x10,
	0x53, 0x49, 0xd5, 0xff, 0x33, 0x1a, 0x56, 0xaf, 0x60, 0x7d, 0x01, 0xf7, 0x2d, 0xea, 0x02, 0xed,
	0x5b, 0x68, 0x2f, 0xb2, 0xe5, 0x9c, 0x2a, 0x0b, 0x6d, 0x1c, 0xa1, 0x79, 0xd5, 0x5b, 0x22, 0x53,
	0x4b, 0xa6, 0xd7, 0x78, 0x02, 0xfd, 0xd9, 0x86, 0xac, 0xd2, 0x0d, 0x93, 0x6a, 0x9a, 0x24, 0x47,
	0x2d, 0xaf, 0xe0, 0x4e, 0x66, 0xcb, 0x9f, 0x3b, 0xaa, 0x34, 0xde, 0x1f, 0xfb, 0xc3, 0xbc, 0xa5,
	0x86, 0x38, 0x6e, 0x4b, 0xfd, 0xc5, 0x9f, 0x60, 0x50, 0x06, 0x5b, 0x49, 0xaf, 0x9d, 0xf6, 0xfa,
	0xe3, 0x9e, 0x86, 0xba, 0xfd, 0xb7, 0x1d, 0xff, 0x0c, 0x8f, 0x0a, 0x78, 0x4c, 0xb7, 0xfc, 0x40,
	0xeb, 0xa5, 0xff, 0x02, 0x8f, 0xcf, 0xf0, 0xf5, 0x14, 0x4c, 0xa0, 0xff, 0x7d, 0xcd, 0x14, 0xbd,
	0xb6, 0xfa, 0x32, 0xb8, 0x76, 0xf5, 0x05, 0xfc, 0xca, 0xea, 0xcf, 0xf0, 0xb5, 0x14, 0x8c, 0xff,
	0x36, 0x01, 0xa6, 0x82, 0x2d, 0xe8, 0xfe, 0xc0, 0x56, 0x14, 0xbd, 0x83, 0xdb, 0xdc, 0xaf, 0xe8,
	0xa1, 0xbe, 0xef, 0xfc, 0x0b, 0x51, 0xcf, 0x39, 0x31, 0x0c, 0xf8, 0x06, 0xbd, 0x87, 0x96, 0x36,
	0x22, 0x32, 0x51, 0xd7, 0xca, 0x11, 0x72, 0x8f, 0x0a, 0xc4, 0x57, 0x08, 0x5c, 0xbb, 0xa0, 0xd0,
	0x08, 0x3b, 0xb7, 0x5f, 0xf4, 0xa4, 0x22, 0x52, 0xd0, 0xcc, 0xe1, 0xc1, 0xc9, 0xd8, 0xd1, 0xd3,
	0xf2, 0xfd, 0x52, 0x3b, 0xa3, 0x67, 0xd5, 0x41, 0x57, 0x96, 0x3b, 0x47, 0x2b, 0xab, 0xc2, 0x17,
	0x56, 0x56, 0xd5, 0xd0, 0x8d, 0xac, 0x93, 0x79, 0x58, 0x59, 0xd5, 0x53, 0xb6, 0xb2, 0x2e, 0x8c,
	0x10, 0xdf, 0xcc, 0xee, 0x7e, 0xb4, 0x86, 0xf9, 0x3b, 0xb6, 0x6c, 0xeb, 0x87, 0xec, 0xc3, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x8d, 0x32, 0x6a, 0xe0, 0x04, 0x00, 0x00,
}
