logger:
  level: INFO
  outputPath: ./log/app.log

grpc:
  host: 0.0.0.0
  port: 9095

db:
  host: psql
  port: 5432
  dbName: antibruteforce
  user: antibruteforce
  password: antibruteforce

limiter:
  login:
    limit: 10
    interval: 60s
  pass:
    limit: 100
    interval: 60s
  ip:
    limit: 1000
    interval: 60s
